[project]
name = "clj-xla-verification"
version = "0.1.0"
requires-python = ">=3.12, <3.14"
dependencies = [
    "gemma @ git+https://github.com/google-deepmind/gemma.git",
    "jax[cpu]",
    "sentencepiece",
    "safetensors",
    "tokenizers==0.22.2",
    "transformers",
    "kagglehub",
    "torch"
]
